language: node_js
node_js:
  - "stable"
after_success: 'npm run coveralls'

dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "apecr-github"

jdk:
  - oraclejdk8
script:
  - npm test
  - npm run coveralls
  - sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'